ALTER TABLE "RuntimeRun"
  ADD COLUMN IF NOT EXISTS "userId" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "ingestTokenHash" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "targetOrigin" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cryptoscanOrigin" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ready',
  ADD COLUMN IF NOT EXISTS "lastEventAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "stoppedAt" TIMESTAMP(3);

ALTER TABLE "RuntimeEvent"
  ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'crypto',
  ADD COLUMN IF NOT EXISTS "keyInfo" TEXT NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "callerScript" TEXT NOT NULL DEFAULT 'unknown:0',
  ADD COLUMN IF NOT EXISTS "hostOrigin" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "scheme" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "port" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "crossOrigin" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "count" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "Finding"
  ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'static',
  ADD COLUMN IF NOT EXISTS "sessionId" TEXT,
  ADD COLUMN IF NOT EXISTS "operation" TEXT,
  ADD COLUMN IF NOT EXISTS "callSite" TEXT,
  ADD COLUMN IF NOT EXISTS "mode" TEXT,
  ADD COLUMN IF NOT EXISTS "curve" TEXT,
  ADD COLUMN IF NOT EXISTS "hash" TEXT,
  ADD COLUMN IF NOT EXISTS "observedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "count" INTEGER NOT NULL DEFAULT 1;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'Finding_sessionId_fkey'
      AND conrelid = '"Finding"'::regclass
  ) THEN
    ALTER TABLE "Finding" ADD CONSTRAINT "Finding_sessionId_fkey"
      FOREIGN KEY ("sessionId") REFERENCES "RuntimeRun"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "Finding_sessionId_idx" ON "Finding"("sessionId");
CREATE INDEX IF NOT EXISTS "RuntimeRun_userId_status_idx" ON "RuntimeRun"("userId", "status");
CREATE INDEX IF NOT EXISTS "RuntimeEvent_runId_source_algorithm_idx" ON "RuntimeEvent"("runId", "source", "algorithm");
